
# Use container_name strictly for human-friendly terminal commands (like docker logs api-monitoring-mongo-service-container or docker exec).

# Use service name (mongo) for ALL internal container-to-container communications (ME_CONFIG_MONGODB_SERVER, MONGO_URI, RABBITMQ_URL, depends_on, etc.).

services:
    postgres:
        image: postgres:16-alpine
        container_name: api-monitoring-postgres-service-container

        # Load credentials securely from .env
        environment:
            POSTGRES_DB: ${PG_DATABASE}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8" # This optional environment variable can be used to send arguments to postgres initdb

        ports:
            - "${PG_PORT}:5432" # "HOST:CONTAINER"

        volumes:
            - postgres_data:/var/lib/postgresql/data # Named Volume
            - ./scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql # Bind Mount
            # scripts in /docker-entrypoint-initdb.d are only run if you start the container with a data directory that is empty; any pre-existing database will be left untouched on container startup. (Reference: https://hub.docker.com/_/postgres)

        networks:
            - api-monitoring-network

        restart: unless-stopped 
        # Restart policy for the service container. Options include: 'no', 'always', 'on-failure', and 'unless-stopped'.

        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}" ]
            interval: 10s
            timeout: 30s # Maximum time to allow one check to run
            retries: 5
            start_period: 0s
            # Every 10 seconds, Docker runs pg_isready inside the container to verify if Postgres is actively accepting connections. If it fails 5 times in a row, Docker marks the container as unhealthy.
            # The start_period is the time Docker waits before starting the health check. During this time, the container is considered starting and is not marked as unhealthy even if the health check fails.

        deploy:   # The `deploy` section is used to configure the resources allocated to the container.
            resources:
                limits:
                    cpus: '1.5'
                    # The container can use at most 1.5 CPU cores simultaneously.
                    # (If your server has 4 cores, Postgres can utilize 100% of core 1 and up to 50% of core 2 (or spread equivalent processing power across cores).
                    # If Postgres tries to use more CPU, Docker throttles (slows down) the container.)
                    memory: 1024M # The container can use at most 1024MB (1GB) of RAM.
                reservations:
                    cpus: '0.25' # The container is guaranteed a minimum of 0.25 CPU core.
                    memory: 256M # The container is guaranteed a minimum of 256MB of RAM.


    # pgAdmin (PostgreSQL web UI)
    pgadmin:
        image: dpage/pgadmin4:8.4
        container_name: api-monitoring-pgadmin-service-container
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - "${PGADMIN_PORT}:80"
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        networks:
            - api-monitoring-network
        restart: unless-stopped
        depends_on:
            - postgres # In Docker Compose, the depends_on property requires the service key name, not the container_name

    
    mongo:
        image: mongo:8.3.7
        container_name: api-monitoring-mongo-service-container
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - "${MONGO_PORT}:27017"
        volumes:
            - mongo_data:/data/db
        networks:
            - api-monitoring-network
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
            interval: 10s
            timeout: 5s
            retries: 5
            # start_period: 0s

        deploy:
            resources:
                limits:
                    cpus: '1.5'
                    memory: 1024M
                reservations:
                    cpus: '0.25'
                    memory: 256M

    mongo-express:
        image: mongo-express
        container_name: api-monitoring-mongo-express-service-container
        ports:
            - "${MONGO_EXPRESS_PORT}:8081"
        environment:
            # Connection settings to MongoDB container
            ME_CONFIG_MONGODB_SERVER: mongo # use service name for internal container-to-container communication
            ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_DATABASE}
            
            # Web Interface Basic Auth Login Credentials
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
        networks:
            - api-monitoring-network

        healthcheck:
            test: [ "CMD-SHELL", "curl -f http://localhost:${MONGO_EXPRESS_PORT}" ]
            interval: 30s
            timeout: 10s
            retries: 5

        restart: unless-stopped
        depends_on:
            - mongo
    

    # RabbitMQ Message Queue
    rabbitmq:
        image: rabbitmq:4.3.4-management-alpine
        container_name: api-monitoring-rabbitmq-service-container
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
        ports:
            - "5672:5672" # AMQP port
            - "15672:15672" # Management UI
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - api-monitoring-network
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
            interval: 30s
            timeout: 10s
            retries: 5


    # Backend Node.js Application   
    api-monitoring-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api-monitoring-app-service-container

        # Passing environment variables here so that the Node.js process running inside the container can read process.env.*
        env_file:
            - .env
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - ./logs:/app/logs
        networks:
            - api-monitoring-network
        depends_on:
            postgres:
                condition: service_healthy
            mongo:
                condition: service_healthy  
            rabbitmq:
                condition: service_healthy

        restart: unless-stopped

        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
            interval: 30s
            timeout: 10s
            retries: 3

volumes:
    postgres_data:
        driver: local
    pgadmin_data:
        driver: local
    mongo_data:
        driver: local
    rabbitmq_data:
        driver: local
        

networks:
    api-monitoring-network:
        driver: bridge